<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Authors>Cycrow</Authors>
    <Company>-</Company>
    <Version>1.0.0.0</Version>
    <Description>Synchronisiert Ausrüstung für FFXIV Rollen.</Description>
    <PackageProjectUrl>https://github.com/ThymmRayne/RoleGearSync_Solution</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Wir unterdrücken die MSB3245 Warnung, da wir die DLLs manuell laden -->
    <NoWarn>$(NoWarn);MSB3245</NoWarn>
    <DalamudLibPath>$(AppData)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Dalamud.Bindings.ImGui">
      <HintPath>$(DalamudLibPath)Dalamud.Bindings.ImGui.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HexaGen.Runtime">
      <HintPath>$(DalamudLibPath)HexaGen.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>