<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>Cycrow</Authors>
    <Company>-</Company>
    <Version>1.0.0.0</Version>
    <Description>Synchronizes gear sets for all jobs within a role.</Description>
    <PackageProjectUrl>https://github.com/ThymmRayne/RoleGearSync_Solution</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
</Project>